items:
  - color: Rose Embroidery
    brand: Chithra's Sarees for Her
    price: ₹1,800.00
    title: Premium Tissue Striped Saree with Rose Embroidery
    link: /
    id: e1u6sdenq1
    condition: featured
    availability: in stock
    description: "SKKV Premium Tissue Striped Saree with Rose Embroidery Comes with
      Plain Running Blouse Discount cost: 1499/- With FREESHIPPING"
    image_link: https://scontent.fmaa2-1.fna.fbcdn.net/v/t45.5328-4/729522687_2265609830876637_8442579710983912259_n.jpg?stp=dst-jpg_s960x960_tt6&_nc_cat=102&ccb=1-7&_nc_sid=247b10&_nc_ohc=NKwrYu7gL9UQ7kNvwHQs-Fg&_nc_oc=AdqNvdfSLnU_3D5i2nN_4K4_ZFII9qyDTJemNP5BZ6B29Zn6QTGXfIuMEqE_Xl_sLbN9xBr3Z79sJJ56bmuTBtSQ&_nc_zt=23&_nc_ht=scontent.fmaa2-1.fna&_nc_gid=aHSWika4y-CLGboSJrUpsA&_nc_ss=7b2a8&oh=00_AQCU2bbENqlo1YXc8G0qjqL5vOU8xJn17Qc-5YmVeGIjzQ&oe=6A5C41B7
